### PR TITLE
i18n: Added Hindi translation

### PR DESCRIPTION
**Pull request by Scrambled777**
This PR adds Hindi `hi` language translation.

### CODE REVIEW

**Review by edfloreshz — APPROVED** [review]
LGTM

**Comment by edfloreshz** [comment]
Thanks! 🎉

**Comment by Scrambled777** [comment]
@edfloreshz,this PR is merged, but I'm not able to see translations in your main branch. Am I missing something?

**Comment by Scrambled777** [comment]
> I'm not sure what happened but that should fix it.

Thank you very much for quick response and fix.

**Pull request merged**
