### PR TITLE
fix README.md typo

### PR DESCRIPTION
**Pull request by hoangph271**

### CODE REVIEW

**Comment by edfloreshz** [comment]
Why is this is modifying Cargo.lock?

**Comment by hoangph271** [comment]
@edfloreshz whoops, sorry

I created the PR and THEN pushed a new commit to my repo to update `libcosmic` to make [double click to maximize](https://github.com/pop-os/libcosmic/commit/8e67f3ce1c0e953c444a2ec43e70a78abcf17400) works

but I pushed to the same branch and didn't realize the effect.

should I close this PR and create another one ?
or should I revert the commit ?

**Comment by edfloreshz** [comment]
You can rebase interactive and delete the commit from this branch 👍🏼 if you find it easier you could also open a new PR.

**Comment by edfloreshz** [comment]
On second thought, leave it as is, we probably need to update libcosmic anyway.

**Pull request merged**
